on: [push] # push 代码时触发
jobs: 
    deploy: 
        runs-on: ubuntu-latest
        name: Tencent Cloudbase Github Action Example
        steps: 
        - name: Checkout
          uses: actions/checkout@v2
        # 使用云开发 Github Action 部署
        - name: Deploy static to Tencent CloudBase
          id: deployStatic
          uses: TencentCloudBase/cloudbase-action@v2.0.1
          with: 
            # 云开发的访问密钥 secretId 和 secretKey
            secretId: ${{ secrets.AKIDHON7evwhKm0z85lDRP7dstgDAtPgleHJ }}
            secretKey: ${{ secrets.rTt7Azc0A7sPgh8JF0dYFgu7kGZv2ubJ }}
            # 云开发的环境id
            envId: ${{ secrets.first-try-5gs14d65a8d29b72 }}
