on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Tencent Cloudbase Github Action Example
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Tencent CloudBase
        uses: TencentCloudBase/cloudbase-action@v2.0.1
        with:
          secretId: ${{AKIDHON7evwhKm0z85lDRP7dstgDAtPgleHJ}}
          secretKey: ${{rTt7Azc0A7sPgh8JF0dYFgu7kGZv2ubJ}}
          envId: ${{first-try-5gs14d65a8d29b72}}
